credential:
  firewall_admin:
    username: "your name"
    password: "your password"
  switch_admin:
    username: "your name"
    password: "your password"
  wireless_admin:
    username: "your name"
    password: "your password"