credential:
  firewall_admin:
    username: "admin"
    password: "Cie@198500"
  switch_admin:
    username: "your name"
    password: "your password"
  wireless_admin:
    username: "your name"
    password: "your password"