---
username: admin
password: Admin@1234
connection_options:
  napalm:
    extras:
      optional_args: {}
  netmiko:
    extras: {}


logging:
  enabled: true
  level: INFO
  file: logs/nornir.log
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 